### ISSUE TITLE
Unselected image doesn't provide URL parameter, causing an error when validating the blocks.

### ISSUE THREAD

**Issue by alexanderhorner** [editor-js/image#63]
When saving the blocks, the image block without a selected image doesn't provide an URL parameter under file. When an image is selected, it does. With the URL parameter the validator configuration for the image looks something like this:
```JSON
{
"tools": {
  "image": {
    "caption": {
      "type": "string"
    },
    "file": {
      "type": "array",
      "data": {
        "url": "string"
      }
    },
    "stretched": {
      "type": "bool",
      "canBeOnly": [false]
    },
    "withBackground": {
      "type": "bool",
      "canBeOnly": [false]
    },
    "withBorder": {
      "type": "bool",
      "canBeOnly": [false]
    }
  }
}
}
```

And this configuration works fine if an image is selected. The save data should look something like this:
```JSON
{
  "type": "image",
  "data": {
    "file": {
      "url": "uploads/image14.png"
    },
    "caption": "This is the 14th image",
    "withBorder": false,
    "stretched": false,
    "withBackground": false
  }
}
```
Unfortunately, when an image isn't selected, the block returns the save data without url parameter, like this: 
```JSON
{
  "type": "image",
  "data": {
    "file": {},
    "caption": "",
    "withBorder": false,
    "stretched": false,
    "withBackground": false
  }
}
```
This causes the following error with my validator-configuration:
```
PHP Fatal error:  Uncaught EditorJS\EditorJSException: Not found required param `url` in /path/tp/project/vendor/codex-team/editor.js/EditorJS/BlockHandler.php:96
Stack trace:
#0 /path/tp/project/vendor/codex-team/editor.js/EditorJS/BlockHandler.php(157): EditorJS\BlockHandler->validate(Array, Array)
#1 /path/tp/project/vendor/codex-team/editor.js/EditorJS/BlockHandler.php(55): EditorJS\BlockHandler->validate(Array, Array)
#2 /path/tp/project/vendor/codex-team/editor.js/EditorJS/EditorJS.php(126): EditorJS\BlockHandler->validateBlock('image', Array)
#3 /path/tp/project/vendor/codex-team/editor.js/EditorJS/EditorJS.php(96): EditorJS\EditorJS->validateBlocks()
#4 /path/tp/project/editor/uploadArticleData.php(184): EditorJS\EditorJS->__construct('{"time":1581957...', '{\n"tools": {\n\t"...')
#5 {main}
  thrown in /path/tp/project/vendor/codex-team/editor.js/EditorJS/BlockHandler.php on line 96
```
If I missed something and this is intended behavior, please tell me what I did wrong and how I can fix it. If not, please look into this. Both ways, I thank you for creating this plugin and that you took your time to read my issue.

Sincerely,
Alexander Horner

**Comment by alexanderhorner** [comment]
My suspicion, that my configuration was just wrong, turned out to be right. You can just make the parameter optional.

My updated configuration works flawlessly and looks like this:
```JSON
{
"tools": {
  "image": {
    "caption": {
      "type": "string"
    },
    "file": {
      "type": "array",
      "data": {
        "url": {
          "type": "string",
          "required": false
        }
      }
    },
    "stretched": {
      "type": "bool",
      "canBeOnly": [false]
    },
    "withBackground": {
      "type": "bool",
      "canBeOnly": [false]
    },
    "withBorder": {
      "type": "bool",
      "canBeOnly": [false]
    }
  }
}
}
```
My apologies if I wasted your time.
